### ISSUE TITLE
Not working with kernel 6.11.8-300 on Fedora 41

### ISSUE THREAD

**Issue by dantahoua** [jhenriquelc/fedora-vmware-installer#1]
Tried with vmware 17.6.1 and 17.6.0, kernel 6.11.8-300, fedora 41 on Intel 12th gen cpu computer...
Secure boot is enable, I did the mok steps.

Virtual machine monitor (failed)
and
Virtual ethernet  (failed) 
in journalctl -xeu vmware.service...
Any idea? Seems to work for you...

**Comment by jhenriquelc** [comment]
Hi, it stopped working for me too since I updated.
It seems something in the auto install script broke, I'm looking into it.
For now, the workaround is to manually build, install, sign and load the modules... :(
Here's a quick sequence of commands you can run to do all of that (needs to be done every time you load a new kernel):
```bash
cd /opt/vm-host-modules
sudo make clean
sudo make
sudo make install
sudo /usr/src/kernels/`uname -r`/scripts/sign-file sha256 /etc/pki/akmods/private/private_key.priv /etc/pki/akmods/certs/public_key.der /lib/modules/`uname -r`/misc/vmnet.ko
sudo /usr/src/kernels/`uname -r`/scripts/sign-file sha256 /etc/pki/akmods/private/private_key.priv /etc/pki/akmods/certs/public_key.der /lib/modules/`uname -r`/misc/vmmon.ko
sudo modprobe vmmon
sudo modprobe vmnet
sudo systemctl restart vmware*
```

**Comment by dantahoua** [comment]
Thanks, it is working manually, the sign-file part was the part I was missing. :)
Anyway, I will keep an eye on your update, your script is so useful!! :)

**Comment by jhenriquelc** [comment]
I've not been able to find out why it isn't working anymore.
To have something working again as soon as possible, I'll be writing a service that checks the current kernel during boot and reinstalls the modules if necessary.
Sorry for making you wait for a fix.

**Comment by jhenriquelc** [comment]
Just run the installer again ([no need to provide VMware bundle anymore](https://github.com/jhenriquelc/fedora-vmware-installer/commit/edc50ca97accf41fb86c1a90f29a589a8c68b012)) and it should fix the issue in your installation.
Please note that it will prompt you to remove the old script and will delete anything in `/opt/vm-host-modules` to be able to do the reinstallation.
